name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write  # Required for OIDC token generation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mukul975'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Verify OIDC token for GitHub Packages
      run: |
        echo "OIDC Token available: ${{ !!secrets.GITHUB_TOKEN }}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Actor: ${{ github.actor }}"

    - name: Create scoped package for GitHub
      run: |
        # Create a scoped package.json for GitHub packages
        cp package.json package.json.backup
        jq '.name = "@mukul975/mcp-web-scrape"' package.json > package-github.json
        mv package-github.json package.json
    
    - name: Publish to GitHub Package Registry with OIDC
      run: |
        echo "Publishing to GitHub Packages with OIDC authentication..."
        npm publish --provenance
        echo "Package published successfully to GitHub Packages"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
    
    - name: Restore original package.json
      run: mv package.json.backup package.json