name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      id-token: write  # Required for OIDC token generation
      packages: write  # Required for GitHub Packages publishing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build

    - name: Verify OIDC token
      run: |
        echo "OIDC Token available: ${{ !!secrets.GITHUB_TOKEN }}"
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Actor: ${{ github.actor }}"

    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Update package.json version
      run: |
        npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
    
    - name: Generate changelog
      id: changelog
      run: |
        # Create changelog entry
        cat > RELEASE_NOTES.md << EOF
        ## [${{ steps.version.outputs.VERSION }}] - $(date +'%Y-%m-%d')
        
        ### What's New
        - Bug fixes and improvements
        - Enhanced performance and stability
        
        ### Installation
        \`\`\`bash
        npm install -g mcp-web-scrape@${{ steps.version.outputs.VERSION }}
        \`\`\`
        
        ### Documentation
        - [README](https://github.com/mukul975/mcp-web-scrape#readme)
        - [Examples](https://github.com/mukul975/mcp-web-scrape/tree/main/examples)
        EOF
    
    - name: Update CHANGELOG.md
      run: |
        # Create a temporary file with the new entry
        cat RELEASE_NOTES.md > temp_changelog.md
        echo "" >> temp_changelog.md
        
        # Append existing changelog if it exists
        if [ -f CHANGELOG.md ]; then
          # Skip the first few header lines and append the rest
          tail -n +7 CHANGELOG.md >> temp_changelog.md
        fi
        
        # Create the final changelog with header
        cat > CHANGELOG.md << 'EOF'
        # Changelog
        
        All notable changes to this project will be documented in this file.
        
        The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
        and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
        
        EOF
        
        # Append the new content
        cat temp_changelog.md >> CHANGELOG.md
        rm temp_changelog.md
    
    - name: Publish to npm with OIDC provenance
      run: |
        echo "Publishing with OIDC provenance..."
        npm publish --provenance --access public
        echo "Package published successfully with provenance attestation"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_CONFIG_PROVENANCE: true
    
    - name: Setup Node.js for GitHub Package Registry
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@mukul975'
    
    - name: Publish to GitHub Package Registry
      run: |
        # Create a scoped package.json for GitHub packages
        cp package.json package.json.backup
        node -e "const pkg = require('./package.json'); pkg.name = '@mukul975/mcp-web-scrape'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
        npm publish
        # Restore original package.json
        mv package.json.backup package.json
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: Release v${{ steps.version.outputs.VERSION }}
        body_path: RELEASE_NOTES.md
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ steps.version.outputs.VERSION }}
        path: dist/
        retention-days: 30
    
    - name: Notify Discord (optional)
      if: env.DISCORD_WEBHOOK_URL != ''
      run: |
        curl -H "Content-Type: application/json" \
             -d '{
               "embeds": [{
                 "title": "🚀 New Release: v${{ steps.version.outputs.VERSION }}",
                 "description": "MCP Web Scrape has been updated!",
                 "color": 5763719,
                 "fields": [
                   {
                     "name": "Version",
                     "value": "v${{ steps.version.outputs.VERSION }}",
                     "inline": true
                   },
                   {
                     "name": "Install",
                     "value": "`npm install -g mcp-web-scrape@${{ steps.version.outputs.VERSION }}`",
                     "inline": false
                   }
                 ],
                 "url": "https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.VERSION }}"
               }]
             }' \
             ${{ env.DISCORD_WEBHOOK_URL }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

  docker:
    runs-on: ubuntu-latest
    needs: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      if: env.DOCKER_USERNAME != ''
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      if: env.DOCKER_USERNAME != ''
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/mcp-web-scrape:latest
          ${{ secrets.DOCKER_USERNAME }}/mcp-web-scrape:v${{ steps.version.outputs.VERSION }}
        platforms: linux/amd64,linux/arm64
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}